{% set name = "clinker" %}
{% set version = "1.31" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: "v{{ version }}.tar.gz"
  url: https://github.com/Oshlack/Clinker/archive/v{{ version }}.tar.gz
  md5: "5487f99af6b9499c87d4d945e9cd9790"

build:
  skip: True  # [osx or not py27]
  number: 0

requirements:
  run:
    - bpipe
    - samtools
    - star 2.5.3a
    - bioconductor-gviz
    - r-essentials

tests:
  commands:
    - bpipe --help

about:
  home: https://github.com/Oshlack/Clinker
  summary: |
    Clinker is a bioinformatics pipeline that generates a superTranscriptome 
    from popular fusion finder outputs.
  license: GPL3
 
